# ------------------------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------------------------
# library(devtools)
# install_github('ramnathv/rCharts')

require(shiny)
require(pheatmap)
require(RColorBrewer)
require(ggplot2)
require(shinyBS)
require(yaml)
require(whisker)
require(RJSONIO)
# require(shinyIncubator)
# require(rCharts)
library(BioNetStat)
source("progress.R")
source("utils.R")
source("rChartsClass.R")
source("renderChart.R")
source("showOutput.R")
source("Datatables.R")
source("toJSON.R")
#source("cogaCommandLine.R")
#source("networkInference.R")
